[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "matplotlib==3.3.2",
    "mplleaflet==0.0.5",
    "numpy",
    "pandas",
    "scikit-learn",
    "scipy",
]
build-backend = "setuptools.build_meta"